# Far Horizons - disable all non FH maps to not mess with admin commands and votes
# - type: gameMapPool
#   id: DefaultStarlightMapPool
#   maps:
#   - StarlightBagel
#   - StarlightCog
#   - StarlightCork
#   - StarlightHotel
#   - StarlightLagan
#   - StarlightLeth
#   - StarlightLobster
#   - StarlightManor
#   - StarlightMing
#   - StarlightOasis
#   - StarlightOmega
#   - StarlightOrigin
#   - StarlightOrwell
#   - StarlightReach
#   - StarlightSaltern
#   - StarlightStarboard
#   - StarlightKiloton
#   - StarlightElkridge
#   - StarlightPrism
#   - StarlightSilica
#   - StarlightCluster
#   - StarlightBox
# # - StarlightBarratry
# # - StarlightExo
# # - StarlightMarathon
# # - StarlightMeta
# # - StarlightPacked
# # - StarlightFland
