- type: entity
  save: false
  id: ActiveCritBase
  abstract: true
  components:
  - type: ActiveCrit
    crawlDuration: 5 # 5 seconds delay before trying to stand up after falling
    minBlackoutSeconds: 5
    maxBlackoutSeconds: 20 # Blackouts last 5-20 seconds
    minAwakeSeconds: 40
    maxAwakeSeconds: 60 # Time between blackouts lasts 40-60 seconds
    standUpDoafterModifier: 5 # Takes 5x the normal time to stand up
    whisperChance: 1 # 100% chance any message turns into whisper
    fallAfterStandingChance: 0.6 # 60% chance to fall down after standing up
    fallOnUseChance: 0.3 # 30% chance to fall down when using items or devices
    damageOnFall:
      types:
        Blunt: 2.5 # Deal 2.5 blunt every time you fall down, other than when you enter crit
    walkSpeedModifier: 0.3
    sprintSpeedModifier: 0.3 # Move 70% slower
    restrictCombat: true # No combat actions allowed
    requireStandingForHands: true # Needs to stand up to grab items
    speechDistortionStrength: 1 # 100% distorted speech, kinda arbitrary
    adjustTemporaryEyeDamage: 5 # gives target this much eye damage for the duration of crit
    cantUseHandsMessage: active-crit-cant-use-hands
    failedStandUpMessage: active-crit-standup-fail
  - type: MobState
    allowedStates:
    - Alive
    - ActiveCritical
    - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      100: ActiveCritical
      200: Dead
  - type: MobStateActions
    actions:
      ActiveCritical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords