- type: listing
  id: VendorVehicleSecway
  productEntity: VehicleSecwayBatterywithKeys
  cost:
    NTCredit: 1000
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition