using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Shuttles;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }

    public void RescuePing(SpaceRescuePingMessage ping) => RadarScreen.RescuePing(ping); // Far Horizons
}
