- type: disease
  id: DiseaseFoodPoisoning
  name: disease-DiseaseFoodPoisoning-name
  desc: disease-DiseaseFoodPoisoning-desc
  spreadPath: [ NonContagious ]
  stageProb: 0.03
  cureSteps:
  - !type:CureWait
    requiredTicks: 300
  stages:
  - stage: 0
    sensations: [ "disease-sensation-queasy", "disease-sensation-stomach-weird" ]
  - stage: 1
    sensations: [ "disease-sensation-stomach-ache", "disease-sensation-nausea" ]
    symptoms:
    - symptom: SymptomEmoteGroan
      probability: 0.1
  - stage: 2
    sensations: [ "disease-sensation-stomach-hurt", "disease-sensation-sick" ]
    symptoms:
    - symptom: SymptomVomiting
    - symptom: SymptomEmoteGroan
      probability: 0.1
    - symptom: SymptomEmoteMoan
      probability: 0.1

- type: disease
  id: DiseaseNarcolepsySyndrome
  name: disease-DiseaseNarcolepsySyndrome-name
  desc: disease-DiseaseNarcolepsySyndrome-desc
  spreadPath: [ Airborne ]
  airborneInfect: 0.01
  cureSteps:
  - !type:CureConditions
    cureChance: 0.05
    conditions:
    - !type:ReagentCondition
      reagent: Haloperidol
      min: 1
  stages:
  - stage: 0
    sensations: [ "disease-sensation-sleepy" ]
  - stage: 1
    sensations: [ "disease-sensation-sleepy-2", "disease-sensation-sleepy-3" ]
    symptoms:
    - symptom: SymptomNarcolepsy

- type: disease
  id: DiseaseAMIV
  name: disease-DiseaseAMIV-name
  desc: disease-DiseaseAMIV-desc
  spreadPath: [ Contact ]
  contactInfect: 0.005
  contactDeposit: 0.05
  cureSteps:
  - !type:CureConditions
    conditions:
    - !type:ReagentCondition
      reagent: JuiceBanana
      min: 3
  stages:
  - stage: 0
    # no-op
  - stage: 1
    sensations: [ "disease-sensation-sick", "disease-sensation-banana-compulsion" ]
  - stage: 2
    cureSteps:
      - !type:CureWait
        requiredTicks: 200
        cureChance: 0.5
    sensations: [ "disease-sensation-sick", "disease-sensation-banana-compulsion" ]
    symptoms:
    - symptom: SymptomMonkeyShout
    - symptom: SymptomGeneticDamage
