#Base Prototypes

- type: latheRecipe
  abstract: true
  id: BaseArmorRecipe
  completetime: 6
  categories:
  - Armor

- type: latheRecipe
  parent: BaseGoldBorgModuleRecipe
  id: BorgModuleLaserCarbine
  result: BorgModuleLaserCarbine

- type: latheRecipe
  parent: CyborgEndoskeleton
  id: SecborgEndoskeleton
  result: SecborgEndoskeleton

- type: latheRecipePack
  id: FarHorizonsSecBorgRecipePack
  recipes:
  - SecborgEndoskeleton
  - BorgModuleLaserCarbine

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLaserPistol
  result: WeaponLaserPistol
  materials:
    Steel: 1000
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserShotgun
  result: WeaponLaserShotgun
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 800
    Plasma: 100

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: SmokeGrenade
  result: SmokeGrenade # Can't really mix reagents in a recipe. It's a bunch of smoke so should be simple
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeStinger
  result: GrenadeStinger # Rubber.
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 800

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: ClusterBangFull
  result: ClusterBangFull # x3
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 1800
    Plastic: 600
    Silver: 10

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: TearGasGrenade # Teargas is effectively a better smoke grenade, slap some silver on it.
  result: TearGasGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 500
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: ExGrenade
  result: ExGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 500
    Plasma: 100
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeShrapnel
  result: GrenadeShrapnel # Explodes in frags, should need more metal. Also the "better" option for sec to use since it doesn't space.
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 1000
    Plastic: 500
    Plasma: 50
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: EmpGrenade # EXCEEDINGLY lethal to a good chunk of the station, needs to be expensive.
  result: EmpGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 800
    Plasma: 100
    Uranium: 100
    Silver: 200
    Gold: 50

- type: latheRecipe
  parent: BaseArmorRecipe
  id: SecwayArmorLightKit
  result: SecwayArmorLightKit
  categories:
  - LatheArmor
  materials:
    ReinforcedGlass: 1000
    Steel: 500
    Plastic: 500