using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._FarHorizons.Vehicles.Equipment;
using Robust.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Vehicles.Components;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;

namespace Content.Client._FarHorizons.Vehicles.Equipment;

[GenerateTypedNameReferences]
public sealed partial class VehicleEquipmentMenu : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    public VehicleEquipmentMenu()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
    }

    public void UpdateState(VehicleEquipmentUiState state)
    {
        var target = _entityManager.GetEntity(state.Vehicle);
        if (target == null 
        || !_entityManager.TryGetComponent<VehicleModsComponent>(target, out var vmComp)
        || !_entityManager.TryGetComponent<MetaDataComponent>(target, out var metaData)) 
            return;
        
        NameLabel.Text = metaData.EntityName;
        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = true;

        HealthPercent.Text = $"{state.Integrity}%";
        HealthBar.Value = state.Integrity;

        FuelPercent.Text = $"{state.Power}%";
        FuelBar.Value = state.Power;
    }
}