using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.LimbDamage.Components;
using Content.Shared.Body;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.LimbDamage.UI;

[GenerateTypedNameReferences]
public sealed partial class LimbStatusUI : UIWidget
{
    public Action<ProtoId<OrganCategoryPrototype>>? OnSelectedLimb;

    public LimbStatusUI()
    {
        RobustXamlLoader.Load(this);
        LimbTargettingDisplay.OnSelectedLimb += (limb) => OnSelectedLimb?.Invoke(limb);
    }

    public void InitTarget(IPrototypeManager protoMan, IResourceCache resCache, SpriteSystem spriteSys, ProtoId<LimbTargettingPrototype> proto)
    {
        LimbTargettingDisplay.DrawLimbs = new();       

        var targetProto = protoMan.Index(proto);
        LimbTargettingDisplay.DrawDebugBoxes = targetProto.DrawDebugBoxes;
        LimbTargettingDisplay.DrawLimbs =
            targetProto.Limbs.ToDictionary(p => p.Limb, p => new DrawLimb(spriteSys, p.Area, p.Sprites));
        LimbTargettingDisplay.DrawLabels =
            targetProto.Labels.Select(p => new DrawLabel(resCache, p.Text, p.Position, p.FontPath, p.FontSize))
                .ToList();

        LimbTargettingDisplay.DefaultColor = Vector3.One;
        LimbTargettingDisplay.HighlightColor = new Vector3(1f, 1f, 1f);

        LimbTargettingDisplay.WithHealth = true;

        LimbTargettingDisplay.InitShaders(protoMan);
    }

    public void UpdateLimb(ProtoId<OrganCategoryPrototype> limb) => 
        LimbTargettingDisplay.UpdateSelection(limb);
    
    public void SetHealth(Dictionary<ProtoId<OrganCategoryPrototype>, float> damage) =>
        LimbTargettingDisplay.LimbDamage = damage;
}