using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.LimbDamage.Components;
using Content.Shared.Body;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.LimbDamage.UI;

[GenerateTypedNameReferences]
public sealed partial class LimbTargettingUI : UIWidget
{
    private const string BgTexture = "template_small";

    public Action<ProtoId<OrganCategoryPrototype>>? OnSelectedLimb;

    public LimbTargettingUI()
    {
        RobustXamlLoader.Load(this);
        LimbTargettingDisplay.OnSelectedLimb += (limb) => OnSelectedLimb?.Invoke(limb);
    }

    public void InitTarget(IPrototypeManager protoMan, IResourceCache resCache, SpriteSystem spriteSys, ProtoId<LimbTargettingPrototype> proto)
    {
        LimbTargettingDisplay.DrawLimbs = new();

        UpdateTheme();            

        var targetProto = protoMan.Index(proto);
        LimbTargettingDisplay.DrawDebugBoxes = targetProto.DrawDebugBoxes;
        LimbTargettingDisplay.DrawLimbs =
            targetProto.Limbs.ToDictionary(p => p.Limb, p => new DrawLimb(spriteSys, p.Area, p.Sprites));
        LimbTargettingDisplay.DrawLabels =
            targetProto.Labels.Select(p => new DrawLabel(resCache, p.Text, p.Position, p.FontPath, p.FontSize))
                .ToList();
        
        LimbTargettingDisplay.InitShaders(protoMan);
    }

    private void UpdateTheme()
    {
        if (BackgroundPanel.PanelOverride is StyleBoxTexture styleBoxTexture &&
            Theme.TryResolveTexture(BgTexture, out var texture))
            styleBoxTexture.Texture = texture;

        var color = Theme.ResolveColor("slotText");
        if (color != null)
            LimbTargettingDisplay.DefaultColor = new(color.Value.R, color.Value.G, color.Value.B);
    }

    public void UpdateLimb(ProtoId<OrganCategoryPrototype> limb) => 
        LimbTargettingDisplay.UpdateSelection(limb);

    public void ShutdownTarget() => 
        LimbTargettingDisplay.DrawLimbs = new();
    
    protected override void OnThemeUpdated()
    {
        base.OnThemeUpdated();
        UpdateTheme();
    }
}

public sealed class DrawLimb(SpriteSystem spriteSys, Box2 area, List<SpriteSpecifier> sprites)
{
    public Box2 Area = area;
    public List<Texture> Textures = sprites.Select(spriteSys.Frame0).ToList();
}

public sealed class DrawLabel
{
    public string Text;
    public Vector2 Position;
    public VectorFont Font;

    public DrawLabel(IResourceCache resCache, string text, Vector2 position, string fontPath, int fontSize)
    {
        Text = text;
        Position = position;

        var font = resCache.GetResource<FontResource>(fontPath);
        Font = new(font, fontSize);
    }
}