using System.Linq;
using Content.Shared.Preferences;
using Content.Shared.Starlight.TextToSpeech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SymspeechVoiceSelectorWindow : DefaultWindow
    {
        private readonly IPrototypeManager _protoManager;

        public List<VoicePrototype> Voices { get; set; } = [];

        public Action<Symspeech>? OnVoiceSelected;

        public Action? OnPreviewRequested;

        public Symspeech? CurrentVoice { get; private set; } = null;

        private int pitch = 0;
        private float speed = 0.44f;
        private float pause = 0.36f;
        private int polyphony = 1;
        private float volume = 1f;

        public SymspeechVoiceSelectorWindow(List<VoicePrototype> voices)
        {
            _protoManager = IoCManager.Resolve<IPrototypeManager>();

            RobustXamlLoader.Load(this);

            VoiceList.OnItemSelected += OnItemSelected;

            UpdateVoices(voices);

            SearchLine.OnTextChanged += _ => FilterAndUpdateVoices();

            PreviewButton.OnPressed += _ => OnPreviewRequested?.Invoke();

            PitchSlider.OnValueChanged += _ => UpdateValues();
            SpeedSlider.OnValueChanged += _ => UpdateValues();
            PauseSlider.OnValueChanged += _ => UpdateValues();
            PolyphonySlider.OnValueChanged += _ => UpdateValues();
            VolumeSlider.OnValueChanged += _ => UpdateValues();
        }

        private void OnItemSelected(ItemList.ItemListSelectedEventArgs obj)
        {
            if (obj.ItemList.TryGetValue(obj.ItemIndex, out var item) && item.Metadata is VoicePrototype voice)
            {
                var symspeech = new Symspeech(
                    voice: voice.ID,
                    pitch: voice.DefaultPitch,
                    speed: voice.DefaultSpeed,
                    pause: voice.DefaultPause,
                    polyphony: voice.DefaultPolyphony,
                    volume: voice.DefaultVolume
                );

                OnVoiceSelected?.Invoke(symspeech);
                CurrentVoice = symspeech;
                CurrentVoiceLabel.Text =
                    Loc.GetString("voice-selector-current-voice", ("voice", Loc.GetString(voice.Name)));

                PitchSlider.Value = symspeech.Pitch;
                SpeedSlider.Value = symspeech.Speed;
                PauseSlider.Value = symspeech.Pause;
                PolyphonySlider.Value = symspeech.Polyphony;
                VolumeSlider.Value = symspeech.Volume;

                UpdateValues();
            }
        }

        public void FilterAndUpdateVoices()
        {
            var voices = Voices.Where(v =>
                Loc.GetString(v.Name).Contains(SearchLine.Text, StringComparison.InvariantCultureIgnoreCase)).ToList();
            UpdateVoices(voices, updateList: false);
        }

        public void UpdateVoices(List<VoicePrototype> voices, bool updateList = true)
        {
            if (updateList)
            {
                Voices.Clear();
                Voices.AddRange(voices);
            }

            VoiceList.Clear();
            foreach (var voice in voices)
                if(voice.AccessibleForPlayers)
                    VoiceList.AddItem($"{Loc.GetString(voice.Name)}", metadata: voice);

            if (CurrentVoice != null)
                SelectVoice(CurrentVoice);
        }

        public void SelectVoice(Symspeech voice)
        {
            var voiceProto = _protoManager.Index(voice.Voice);
            var item = VoiceList.Where(x => x.Metadata is VoicePrototype voice1 && voice1.ID == voiceProto.ID);
            if (item.Any())
                item.First().Selected = true;

            CurrentVoice = voice;

            PitchSlider.Value = CurrentVoice.Pitch;
            SpeedSlider.Value = CurrentVoice.Speed;
            PauseSlider.Value = CurrentVoice.Pause;
            PolyphonySlider.Value = CurrentVoice.Polyphony;
            VolumeSlider.Value = CurrentVoice.Volume;

            CurrentVoiceLabel.Text = Loc.GetString("voice-selector-current-voice",
                ("voice", Loc.GetString(voiceProto.Name)));
        }

        public void LoadVoice(Symspeech voice)
        {
            var voiceProto = _protoManager.Index(voice.Voice);

            CurrentVoice = voice;

            PitchSlider.Value = voice.Pitch;
            SpeedSlider.Value = voice.Speed;
            PauseSlider.Value = voice.Pause;
            PolyphonySlider.Value = voice.Polyphony;
            VolumeSlider.Value = voice.Volume;

            CurrentVoiceLabel.Text = Loc.GetString("voice-selector-current-voice",
                ("voice", Loc.GetString(voiceProto.Name)));
        }

        public void UpdateValues()
        {
            pitch = (int)MathF.Round(PitchSlider.Value);
            speed = MathF.Round(SpeedSlider.Value, 2);
            pause = MathF.Round(PauseSlider.Value, 2);
            polyphony = (int)MathF.Round(PolyphonySlider.Value);
            volume = MathF.Round(VolumeSlider.Value, 2);

            PitchValueLabel.Text = pitch.ToString("F0");
            SpeedValueLabel.Text = speed.ToString("F2");
            PauseValueLabel.Text = pause.ToString("F2");
            PolyphonyValueLabel.Text = polyphony.ToString("F0");
            VolumeValueLabel.Text = volume.ToString("F2");

            if (CurrentVoice is { } current)
            {
                var updated = new Symspeech(current.Voice, pitch, speed, pause, polyphony, volume);
                CurrentVoice = updated;
                OnVoiceSelected?.Invoke(updated);
            }
        }
    }
}