- type: job
  id: CC-CSDOfficial
  name: job-name-cc-csd-official
  description: job-description-cc-csd-official
  playTimeTracker: JobCC-CSDOfficial
  setPreference: false
  startingGear: CC-CSDGear
  icon: "JobIconCentComm"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CC-CSDGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcomcap
    mask: ClothingMaskGasCentcom
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCentcommCarapace
    back: ClothingBackpackNTNC
    id: CSDOfficialPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltNTNCRigFilled
    suitstorage: WeaponSubMachineGunWt550
    pocket1: MagazinePistolSubMachineGunTopMounted
    suitstorage2: NitrogenTankFilled
  storage:
    autoImplant:
      - MindShieldImplanter
      - DeathRattleImplanterCentcomm