using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Shuttles;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client._FarHorizons.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class GunneryConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedMapSystem _maps;
    
    public event Action<Vector2?>? TargetSelected;
    public event Action<NetCoordinates, List<NetEntity>>? FireButtonPressed;

    private NavInterfaceState? _lastNavState;
    private EntityUid? _shuttleEntity;
    private readonly List<NetEntity> _turrets = [];
    private readonly List<NetEntity> _selectedTurrets = [];

    public GunneryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _maps = _entManager.System<SharedMapSystem>();

        RadarScreen.OnRadarClick += OnFireCommand;
        Startup();
    }

    public void UpdateState(NavInterfaceState scc) 
    {
        RadarScreen.UpdateState(scc);
        _lastNavState = new NavInterfaceState(scc.MaxRange, scc.Coordinates, scc.Angle, scc.Docks);
    }

    public void Update(GunneryConsoleBuiState state)
    {
        _turrets.Clear();
        state.TurretEntities.ForEach(_turrets.Add);

        if (_lastNavState != null)
            RadarScreen.UpdateState(_lastNavState);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        RadarScreen.SetShuttle(shuttle);
    }
    
    public void Startup()
    {
        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            SetMap(_maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        }
    }

    public void SetMap(Vector2 position)
    {
        RadarScreen.SetMap(position);
        RadarScreen.Offset = position;
    }

    private void OnFireCommand(EntityCoordinates position)
    {
        // if (_selectedTurrets.Count == 0)
        //     return;

        FireButtonPressed?.Invoke(_entManager.GetNetCoordinates(position), _selectedTurrets);
    }

    public Vector2? GetMousePosition() => RadarScreen.GetMousePosition();
}
