using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client._FarHorizons.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class GunneryConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedMapSystem _maps;
    
    private EntityUid? _shuttleEntity;

    public GunneryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _maps = _entManager.System<SharedMapSystem>();
        Startup();
    }

    public void UpdateState(NavInterfaceState scc) => RadarScreen.UpdateState(scc);

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        RadarScreen.SetShuttle(shuttle);
    }
    
    public void Startup()
    {
        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            SetMap(_maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        }
    }

    public void SetMap(Vector2 position)
    {
        RadarScreen.SetMap(position);
        RadarScreen.Offset = position;
    }
}
