using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Materials;

namespace Content.Client._FarHorizons.Medical.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly MaterialStorageSystem _materialStorage;
    public EntityUid Entity;
    public VaccinatorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _materialStorage = _entityManager.System<MaterialStorageSystem>();

    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        MaterialsList.SetOwner(Entity);
    }
}