- type: entity
  id: OrganAnimalBrain
  parent: OrganHumanBrain
  name: animal brain
  description: "The source of incredible, unending mischief. Ook."

- type: entity
  id: OrganAnimalEyes
  parent: OrganHumanEyes
  name: animal eyes
  description: "I Spy."

- type: entity
  id: OrganAnimalTongue
  parent: OrganHumanTongue
  name: animal tongue
  description: "A fleshy muscle mostly used for screeching."