- type: antag
  id: SSF
  name: roles-antag-ssf-name
  antagonist: true
  setPreference: false
  objective: roles-antag-ssf-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hour - Far Horizons # Starlight - 72000 # 20h
  #- !type:DepartmentTimeRequirement - #Far Horizons
  #  department: Security
  #  time: 36000 # 10h
  playTimeTracker: AntagSSF
