## Static

- type: latheRecipePack
  id: SyndicateServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - SyndicateUniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - OvenMachineCircuitboard
  - StoveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard