# Far Horizons - disable all non FH maps to not mess with admin commands and votes
# - type: gameMapPool
#   id: DefaultMapPool
#   maps:
#   - Bagel
#   - Box
#   - Elkridge
#   - Fland
#   - Marathon
#   - Oasis
#   - Packed
#   - Plasma
#   - Reach
#   - Exo
#   - Snowball
#   - Serpentcrest
