- type: startingGear
  id: NTNCHardsuitGear
  equipment:
    jumpsuit: ClothingUniformNTNCFatigues
    back: ClothingBackpackNTNC
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterHardsuitNTNCConsortium
    id: NTNCCSPDA
    eyes: ClothingEyesGlassesNTNC
    ears: ClothingHeadsetAltNTNC
    mask: ClothingMaskGasSecurity
    rig: ClothingBeltNTNCRig # FH
    belt: ClothingBeltNTNCFilled # FH
    gloves: ClothingHandsGlovesCombat
    suitstorage: WeaponSubMachineGunWt550
  storage: # far horizons
    autoImplant: # far horizons
      - MindShieldImplanter # far horizons
      - DeathRattleImplanterCentcomm # far horizons
      - RadioImplantNTNC # far horizons

- type: startingGear
  id: NTNCTrainerGear
  equipment:
    jumpsuit: ClothingUniformNTNCFatigues
    back: ClothingBackpackNTNC
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretCommand
    outerClothing: ClothingOuterHardsuitNTNCConsortium
    id: NTNCCSPDA
    eyes: ClothingEyesGlassesNTNC
    ears: ClothingHeadsetAltNTNC
    mask: ClothingMaskGasSecurity
    rig: ClothingBeltNTNCRig # FH
    belt: ClothingBeltNTNCFilled # FH
    gloves: ClothingHandsGlovesCombat
    suitstorage: WeaponSubMachineGunWt550
  storage: # far horizons
    autoImplant: # far horizons
      - MindShieldImplanter # far horizons
      - DeathRattleImplanterCentcomm # far horizons
      - RadioImplantNTNC # far horizons

- type: startingGear
  id: NTNCBasicGear
  equipment:
    jumpsuit: ClothingUniformNTNCFatigues
    back: ClothingBackpackNTNC
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetHardsuitNTNCConsortium
    outerClothing: ClothingOuterVestNTNC
    id: NTNCCSPDA
    eyes: ClothingEyesGlassesNTNC
    ears: ClothingHeadsetAltNTNC
    mask: ClothingMaskGasSecurity
    rig: ClothingBeltNTNCRig # FH
    belt: ClothingBeltNTNCFilled # FH
    gloves: ClothingHandsGlovesCombat
    suitstorage: WeaponSubMachineGunWt550
  storage: # far horizons
    autoImplant: # far horizons
      - MindShieldImplanter # far horizons
      - DeathRattleImplanterCentcomm # far horizons
      - RadioImplantNTNC # far horizons

- type: startingGear
  id: NTNCMedicGear
  equipment:
    jumpsuit: ClothingUniformNTNCFatigues
    back: ClothingBackpackNTNC
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterHardsuitNTNCConsortiumMedic
    id: NTNCCSPDA
    eyes: ClothingEyesGlassesNTNC
    ears: ClothingHeadsetAltNTNC
    mask: ClothingMaskGasSecurity
    rig: ClothingBeltNTNCRig # FH
    belt: ClothingBeltNTNCFilledMed # FH
    gloves: ClothingHandsGlovesCombat
    suitstorage: WeaponSubMachineGunWt550
  storage: # far horizons
    autoImplant: # far horizons
      - MindShieldImplanter # far horizons
      - DeathRattleImplanterCentcomm # far horizons
      - RadioImplantNTNC # far horizons