#region Detective Scurret

- type: startingGear
  id: DetectiveScurretGear
  equipment:
    id: DetectivePDA
    head: ClothingHeadHatFedoraGrey
    neck: ClothingNeckTieDet
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ClothingOuterVestDetective
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterScugFilled
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesForensic