## Static recipes

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: FarHorizonsSecurityPracticeStatic
  recipes:
  - MagazinePistol38Practice
  - MagazineBoxRevolver38Practice
  - MagazineRifle38Practice
  - SpeedLoaderRevolver38Practice
  - MagazineMagnumPractice

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: FarHorizonsSecurityAmmoStatic
  recipes:
######################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleRubber
# Rifle
  - MagazineBoxRifleRubber
# Pistol
  - MagazineBoxPistolRubber
  - MagazineBoxRevolver38Rubber
# Magnum
  - MagazineBoxMagnumRubber
#####################MAGAZINE#######################
# Pistol
  - MagazinePistol38Rubber
  - MagazinePistolRubber
  - SpeedLoaderRevolver38Rubber
  - SpeedLoaderRevolver38Empty
  - SpeedLoaderRevolver38SP
  - SpeedLoaderRevolver38HP
  - SpeedLoaderRevolver38FMJ
# Rifle
  - MagazineRifle38Empty 
  - MagazineRifle38SP 
  - MagazineRifle38HP 
  - MagazineRifle38FMJ 
  - MagazineRifle38Rubber
# Shotgun
  - BoxBeanbag
# Magnum
  - MagazineMagnumHP
  - MagazineMagnumFMJ
  - MagazineMagnumRubber

## Dynamic recipes
- type: latheRecipePack
  id: FarHorizonsSecurityWeaponsDynamic
  recipes:
  - WeaponLaserPistol
  - WeaponLaserShotgun

- type: latheRecipePack
  id: FarHorizonsSecurityThrowablesDynamic
  recipes:
  - GrenadeFlashBang
  - ClusterBangFull
  - ExGrenade
  - EmpGrenade
  - SmokeGrenade
  - TearGasGrenade
  - GrenadeStinger
  - GrenadeShrapnel

- type: latheRecipePack
  id: FarHorizonsSecurityArmorDynamic
  recipes:
  - SecwayArmorLightKit
# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: FarHorizonsSecurityAmmoDynamic
  recipes:
#####################BOX#######################
# Pistol
  - MagazineBoxRevolver38Incendiary
  - MagazineBoxRevolver38Uranium

#####################MAGAZINE#######################
# Magnum
  - MagazineMagnumIncendiary
  - MagazineMagnumUranium
  - MagazineMagnumAP
# Pistol
  - MagazinePistol38Incendiary
  - MagazinePistol38Uranium
# Pistol - Speedloader
  - SpeedLoaderRevolver38Incendiary
  - SpeedLoaderRevolver38Uranium
  - SpeedLoaderRevolver38AP
# Rifle
  - MagazineRifle38Incendiary 
  - MagazineRifle38Uranium  
  - MagazineRifle38AP  
# Grenade

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagStatic
  recipes:
# Magazine
  - L6SawMagazine
  - MagazineLightRifleSP
  - MagazineLightRifleHP
  - MagazineLightRifleFMJ
  - MagazineLightRifleMaxim
  - MagazineLightRifleEmpty
  - MagazinePistolSubMachineGunUzi
  - MagazinePistolSubMachineGunPPSH
  - MagazineMagnumRifleSP
# Box
  - MagazineBoxCaselessRifle
  - MagazineBoxCaselessRifleRubber
  - MagazineBoxCaselessRiflePractice
  - MagazineBoxLightRiflePractice

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagDynamic
  recipes:
# Magazine
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazineLightRifleAP