## Static recipes

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: FarHorizonsSecurityPracticeStatic
  recipes:
  - MagazinePistol40Practice
  - MagazineBoxPistol40Practice
  - MagazineRifle40Practice
  - SpeedLoaderPistol40Practice
  - MagazineMagnumPractice

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: FarHorizonsSecurityAmmoStatic
  recipes:
######################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleRubber
# Rifle
  - MagazineBoxRifleRubber
# Pistol
  - MagazineBoxPistolRubber
  - MagazineBoxPistol40Rubber
# Magnum
  - MagazineBoxMagnumRubber
#####################MAGAZINE#######################
# Pistol
  - MagazinePistol40Rubber
  - MagazinePistolRubber
  - SpeedLoaderPistol40Rubber
  - SpeedLoaderPistol40Empty
  - SpeedLoaderPistol40SP
  - SpeedLoaderPistol40HP
  - SpeedLoaderPistol40FMJ
# Rifle
  - MagazineRifle40Empty 
  - MagazineRifle40SP 
  - MagazineRifle40HP 
  - MagazineRifle40FMJ 
  - MagazineRifle40Rubber
# Shotgun
  - BoxBeanbag
# Magnum
  - MagazineMagnumHP
  - MagazineMagnumFMJ
  - MagazineMagnumRubber

## Dynamic recipes
- type: latheRecipePack
  id: FarHorizonsSecurityWeaponsDynamic
  recipes:
  - WeaponLaserPistol
  - WeaponLaserShotgun

- type: latheRecipePack
  id: FarHorizonsSecurityThrowablesDynamic
  recipes:
  - GrenadeFlashBang
  - ClusterBangFull
  - ExGrenade
  - EmpGrenade
  - SmokeGrenade
  - TearGasGrenade
  - GrenadeStinger
  - GrenadeShrapnel

- type: latheRecipePack
  id: FarHorizonsSecurityArmorDynamic
  recipes:
  - SecwayArmorLightKit
# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: FarHorizonsSecurityAmmoDynamic
  recipes:
#####################BOX#######################
# Pistol
  - MagazineBoxPistol40Incendiary
  - MagazineBoxPistol40Uranium

#####################MAGAZINE#######################
# Magnum
  - MagazineMagnumIncendiary
  - MagazineMagnumUranium
  - MagazineMagnumAP
# Pistol
  - MagazinePistol40Incendiary
  - MagazinePistol40Uranium
# Pistol - Speedloader
  - SpeedLoaderPistol40Incendiary
  - SpeedLoaderPistol40Uranium
  - SpeedLoaderPistol40AP
# Rifle
  - MagazineRifle40Incendiary 
  - MagazineRifle40Uranium  
  - MagazineRifle40AP  
# Grenade

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagStatic
  recipes:
# Magazine
  - L6SawMagazine
  - MagazineLightRifleSP
  - MagazineLightRifleHP
  - MagazineLightRifleFMJ
  - MagazineLightRifleMaxim
  - MagazineLightRifleEmpty
  - MagazinePistolSubMachineGunUzi
  - MagazinePistolSubMachineGunPPSH
  - MagazineMagnumRifleSP
# Box
  - MagazineBoxCaselessRifle
  - MagazineBoxCaselessRifleRubber
  - MagazineBoxCaselessRiflePractice
  - MagazineBoxLightRiflePractice

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagDynamic
  recipes:
# Magazine
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazineLightRifleAP