- type: listing
  id: ClothingHandsGlovesCombat
  productEntity: ClothingHandsGlovesCombat
  cost:
    NTCredit: 399
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition

- type: listing
  id: ClothingHeadHelmetDredd
  productEntity: ClothingHeadHelmetDredd
  cost:
    NTCredit: 300
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition
