using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Client.UserInterface.Systems.Guidebook;
// Cosmatic Drift Record System-start
using Content.Client._CD.Records.UI;
using Content.Shared._CD.Records;
// Cosmatic Drift Record System-end
using Content.Shared.CCVar;
using Content.Shared.Guidebook;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

#region Starlight
using Content.Shared.Starlight.CCVar;
using Content.Shared.Starlight.TextToSpeech;
using Content.Shared._Starlight.Traits;
#endregion Starlight
using Content.Shared._FarHorizons.Factions;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly ISharedFactionManager _factions; // Far Horizons

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private readonly ISawmill _sawmill;

        private List<VoicePrototype> _voices = [];

        private List<VoicePrototype> _siliconVoices = []; // 🌟Starlight🌟

        // Cosmatic Drift Record System-start
        private readonly RecordEditorGui _recordsTab; // Tracks CD records UI state
        // Cosmatic Drift Record System-end

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings,
            ISharedFactionManager factions) // Far Horizons
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _requirements = requirements;
            _factions = factions; // Far Horizons
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            //begin starlight
            _allowCharacterSecrets = _cfgManager.GetCVar(StarlightCCVars.ICSecrets);
            _allowExploitables = _cfgManager.GetCVar(StarlightCCVars.ExploitableSecrets);
            _allowRPNotes = _cfgManager.GetCVar(StarlightCCVars.OOCNotes);

            OOCInfoTab.Visible = _allowRPNotes;
            ICInfoTab.Visible = _allowFlavorText || _allowExploitables || _allowCharacterSecrets;
            //end starlight
            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                Preview.ExportImage(args.Button);
            };

            OpenImagesButton.OnPressed += args =>
            {
                resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            Traits.OnTraitsChanged += OnTraitsSelectionChanged; // Starlight

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            // Starlight - Start
            #region Custom Specie Name

            CCustomSpecieNameEdit.OnTextChanged += args => { SetCustomSpecieName(args.Text); };

            #endregion CustomSpecieName
            // Starlight - End

            #region Appearance

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
                UpdateCustomSpecieNameEdit(); // Starlight
            };

            UpdateSubspecies();
            // Far Horizons start
            SubspeciesButton.OnItemSelected += args =>
            {
                SubspeciesButton.SelectId(args.Id);
                SetSpecies(_subspecies[args.Id].ID);
                UpdateCustomSpecieNameEdit(); // Starlight
            };
            // Far Horizons end

            //starlight start
            #region Size
            UpdateSizeControls();

            WidthSlider.OnValueChanged += args =>
            {
                SetWidth(args.Value);
            };

            HeightSlider.OnValueChanged += args =>
            {
                SetHeight(args.Value);
            };

            WidthResetButton.OnPressed += _ =>
            {
                if (Profile is null) return;
                if (_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var speciesPrototype)) WidthSlider.Value = speciesPrototype.DefaultWidth;
            };

            HeightResetButton.OnPressed += _ =>
            {
                if (Profile is null) return;
                if (_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var speciesPrototype)) HeightSlider.Value = speciesPrototype.DefaultHeight;
            };
            #endregion Size
            //starlight end

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor, Profile.Appearance.EyeGlowing); // Far Horizons
                ReloadProfilePreview();
            };

            //starlight start
            EyeColorPicker.OnGlowingChanged += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeGlowing(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor, Profile.Appearance.EyeGlowing); // Far Horizons
                ReloadProfilePreview();
            };
            //starlight end

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            // Far Horizons
            _jobCategories = [];

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            // RefreshTraits(); - Starlight

            #region Markings



            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            // Starlight
            #region Cybernetics
            Cybernetics.OnCyberneticsUpdated += OnCyberneticsUpdated;
            #endregion Cybernetics

            RefreshCharacterInfo();

            #region Dummy

            // Far Horizons factions
            Preview.Initialize(this, _entManager, _preferencesManager, _prototypeManager, _playerManager, _factions);

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;

            // Far Horizons - Disabled voices in UI only
            // //🌟Starlight🌟
            // _voices = _prototypeManager
            //     .EnumeratePrototypes<VoicePrototype>()
            //     .Where(o => !o.Silicon)
            //     .ToList();

            // VoiceButton.OnItemSelected += args =>
            // {
            //     VoiceButton.SelectId(args.Id);
            //     Profile = Profile?.WithVoice(_voices[args.Id].ID);
            //     IsDirty = true;
            // };
            // VoicePreviewButton.OnPressed +=
            //     _ => _entManager.System<TextToSpeechSystem>().RequestPreviewTts(Profile?.Voice ?? "");

            // // 🌟Starlight🌟 start
            // _siliconVoices = _prototypeManager
            //     .EnumeratePrototypes<VoicePrototype>()
            //     .Where(o => o.Silicon)
            //     .ToList();

            // SiliconVoiceButton.OnItemSelected += args =>
            // {
            //     SiliconVoiceButton.SelectId(args.Id);
            //     Profile = Profile?.WithSiliconVoice(_siliconVoices[args.Id].ID);
            //     IsDirty = true;
            // };
            // SiliconVoicePreviewButton.OnPressed +=
            //     _ => _entManager.System<TextToSpeechSystem>().RequestPreviewTts(Profile?.SiliconVoice ?? "");

            SetupTabs();

            // Cosmatic Drift Record System-start
            _recordsTab = CreateRecordEditorTab(); // Instantiate the CD record editor UI
            // Cosmatic Drift Record System-end
            SetupInfoEditors();
            RefreshCharacterInfo();
            // 🌟Starlight🌟 end
        }
        // private void UpdateVoicesControls()
        // {
        //     if (Profile is null)
        //         return;

        //     VoiceButton.Clear();

        //     for (var i = 0; i < _voices.Count; i++)
        //     {
        //         var voice = _voices[i];

        //         VoiceButton.AddItem($"[{voice.Sex}] {Loc.GetString(voice.Name)}", i);
        //     }

        //     if (string.IsNullOrEmpty(Profile.Voice))
        //     {
        //         var available = _voices.ToArray();
        //         if (available.Length > 0)
        //         {
        //             var index = new Random().Next(0, available.Length);
        //             Profile.Voice = available[index].ID;
        //         }
        //     }
        //     var voiceChoiceId = _voices.FindIndex(x => x.ID == Profile.Voice);
        //     if (voiceChoiceId != -1)
        //         VoiceButton.TrySelectId(voiceChoiceId);
        // }
        // 🌟Starlight🌟 Start

        private void SetupTabs()
        {
            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));
            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));
            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));
            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab"));
            TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-markings-tab"));
            TabContainer.SetTabTitle(5, Loc.GetString("humanoid-profile-editor-cybernetics-tab"));
            TabContainer.SetTabTitle(6, Loc.GetString("humanoid-profile-editor-ic-info-tab"));
            TabContainer.SetTabTitle(7, Loc.GetString("humanoid-profile-editor-ooc-info-tab"));
        }
        // Cosmatic Drift Record System-start: Build the CD record editor tab and hook persistence callbacks
        private RecordEditorGui CreateRecordEditorTab()
        {
            // Create the record editor in code so that we can provide a callback for saving edits back to the profile.
            var recordEditor = new RecordEditorGui(UpdateProfileRecords)
            {
                HorizontalExpand = true,
                VerticalExpand = true
            };

            TabContainer.AddChild(recordEditor);
            TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-cd-records-tab"));
            recordEditor.Update(Profile);
            return recordEditor;
        }
        // Cosmatic Drift Record System-end

        // private void UpdateSiliconVoicesControls()
        // {
        //     if (Profile is null)
        //         return;

        //     SiliconVoiceButton.Clear();

        //     for (var i = 0; i < _siliconVoices.Count; i++)
        //     {
        //         var voice = _siliconVoices[i];

        //         SiliconVoiceButton.AddItem($"[{voice.Sex}] {Loc.GetString(voice.Name)}", i);
        //     }

        //     if (string.IsNullOrEmpty(Profile.SiliconVoice))
        //     {
        //         var available = _siliconVoices.ToArray();
        //         if (available.Length > 0)
        //         {
        //             var index = new Random().Next(0, available.Length);
        //             Profile.SiliconVoice = available[index].ID;
        //         }
        //     }

        //     var siliconVoiceChoiceId = _siliconVoices.FindIndex(x => x.ID == Profile.SiliconVoice);
        //     if (siliconVoiceChoiceId != -1)
        //         SiliconVoiceButton.TrySelectId(siliconVoiceChoiceId);
        // }


        private void SetupInfoEditors()
        {
            ICInfoEditor.PhysicalDescInput.OnTextChanged += OnPhysicalDescChanged;
            ICInfoEditor.PersonalityDescInput.OnTextChanged += OnPersonalityDescChanged;
            ICInfoEditor.ExploitableInput.OnTextChanged += OnExploitablesChanged;
            ICInfoEditor.SecretsInput.OnTextChanged += OnSecretsChanged;


            OOCInfoEditor.PersonalNotesInput.OnTextChanged += OnPersonalNotesChanged;
            OOCInfoEditor.OOCNotesInput.OnTextChanged += OnOOCNotesChanged;
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        public void RefreshCharacterInfo()
        {
            if (ICInfoEditor.VisibleInTree)
            {
                ICInfoEditor.Physical.Visible = _allowFlavorText;
                ICInfoEditor.Personality.Visible = _allowFlavorText;
                ICInfoEditor.Secrets.Visible = _allowCharacterSecrets;
                ICInfoEditor.Exploitable.Visible = _allowCharacterSecrets;
            }
            if (OOCInfoEditor.VisibleInTree)
            {
                OOCInfoEditor.OOCNotes.Visible = _allowRPNotes;
                OOCInfoEditor.PersonalNotes.Visible = _allowRPNotes;
            }
        }

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _savedProfile?.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            Preview.ReloadPreview();

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;
            AntagOverride = null; // Starlight: Antag Loadouts

            UpdateNameEdit();
            UpdateSubspecies(); // Far Horizons
            UpdateCustomSpecieNameEdit(); // Starlight
            UpdateCharacterInfoEditorText(); //Starlight
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSizeControls(); //starlight
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            //UpdateHairPickers();
            //UpdateCMarkingsHair();
            //UpdateCMarkingsFacialHair();
            //UpdateVoicesControls();
            //UpdateSiliconVoicesControls(); // 🌟Starlight🌟
            UpdateCybernetics(); // Starlight
            UpdateSpeciesLoadout(); // Far Horizons

            UpdateTraitsSelection(); // Starlight
            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            //RefreshTraits(); - Starlight
            // Ensure the record editor reflects the freshly-loaded profile data.
            // Cosmatic Drift Record System-start
            _recordsTab.Update(Profile); // Refresh record editor when a profile is loaded
            // Cosmatic Drift Record System-end
            RefreshCharacterInfo(); //starlight
            Preview.Initialize(this, _entManager, _preferencesManager, _prototypeManager, _playerManager, _factions); // Far Horizons factions
            ReloadPreview();
        }

        /// <summary>
        /// Load the profile located at the slot into the profile editor
        /// </summary>
        /// <param name="slot">slot's profile to load</param>
        public void SetProfile(int slot)
        {
            if (_preferencesManager.Preferences == null)
                return;
            if (!_preferencesManager.Preferences!.TryGetHumanoidInSlot(slot, out var humanoid))
                return;
            _savedProfile = humanoid.Clone();
            SetProfile(humanoid, slot);
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            Preview.ReloadProfilePreview();

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }
    }
}

