using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared._FarHorizons.Factions;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// <summary>
/// UI class to handle the selection of a player's job priorities.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class JobPriorityEditor : BoxContainer
{
    private readonly IClientPreferencesManager _preferencesManager;
    private readonly IPrototypeManager _prototypeManager;
    private readonly JobRequirementsManager _requirements;
    private readonly ISharedFactionManager _factions; // Far Horizons

    /// <summary>
    /// A dictionary to map Department names / Categories to a box that holds individual job priority selector controls
    /// </summary>
    /// Far Horizons
    private readonly Dictionary<(ProtoId<FactionPrototype>, string), BoxContainer> _jobCategories = new();

    /// <summary>
    /// A list holding each RequirementsSelector and the name of the job it is setting the priority for.
    /// </summary>
    /// Far Horizons
    private readonly List<((ProtoId<FactionPrototype>, ProtoId<JobPrototype>), RequirementsSelector)> _jobPriorities = new();

    /// <summary>
    /// The currently edited job priorities dictionary that matches the format of PlayerPreferences job priorities.
    /// </summary>
    /// Far Horizons
    public Dictionary<(ProtoId<FactionPrototype>, ProtoId<JobPrototype>), JobPriority> SelectedJobPriorities { get; private set; } = new();

    /// <summary>
    /// Event that is invoked when the player clicks "Save"
    /// </summary>
    /// Far Horizons
    public event Action<Dictionary<(ProtoId<FactionPrototype>, ProtoId<JobPrototype>), JobPriority>>? Save;

    /// <summary>
    /// Create a new job priority editor
    /// </summary>
    public JobPriorityEditor(
        IClientPreferencesManager preferencesManager,
        IPrototypeManager prototypeManager,
        JobRequirementsManager requirements,
        ISharedFactionManager factions // Far Horizons
        )
    {
        _prototypeManager = prototypeManager;
        _requirements = requirements;
        _preferencesManager = preferencesManager;
        _factions = factions; // Far Horizons
        RobustXamlLoader.Load(this);

        ResetButton.OnPressed += args =>
        {
            SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone() ??  [];
            UpdateJobPriorities();
            CheckDirty();
        };

        SaveButton.OnPressed += args =>
        {
            Save?.Invoke(SelectedJobPriorities);
            UpdateJobPriorities();
            CheckDirty();
        };

        RefreshJobs();
    }


    /// <summary>
    /// Refreshes all job selectors.
    /// </summary>
    public void RefreshJobs()
    {
        JobList.DisposeAllChildren();
        _jobCategories.Clear();
        _jobPriorities.Clear();

        var selectorPriorities = new[]
        {
            ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
            ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
            ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
            ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
        };

        // Far Horizons - factions
        Dictionary<ProtoId<FactionPrototype>, BoxContainer> faction_tabs = new();
        foreach (var faction in _factions.ListPlayableFactions().ToList())
        {
            var faction_tab = new ScrollContainer
            {
                VerticalExpand = true,
                Name = faction.Name,
                ToolTip = Loc.GetString(faction.Description)
            };

            JobList.AddChild(faction_tab);

            var faction_tab_content = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
            };

            faction_tab.AddChild(faction_tab_content);

            faction_tabs.Add(faction, faction_tab_content);
        }

        foreach (var dptAssignment in _factions.ListFactionDepartments()
                                            .Where(p => _factions.ListPlayableFactions()
                                                .Any(e => e.ID == p.Faction))
                                                .OrderBy(p => p.Weight)
                                                .ThenBy(p => p.Department))
        {
            if (!_prototypeManager.TryIndex<DepartmentPrototype>(dptAssignment.Department, out var department) ||
                !_prototypeManager.TryIndex<FactionPrototype>(dptAssignment.Faction, out var faction))
                    continue;

            var departmentName = Loc.GetString(department.Name);

            // If a department category hasn't yet been created in _jobCategories,
            // start a new one.
            if (!_jobCategories.TryGetValue((faction.ID, department.ID), out var category))
            {
                category = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    Name = department.ID,
                };

                category.AddChild(new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat {BackgroundColor = Color.FromHex("#464966")},
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                ("departmentName", departmentName)),
                            Margin = new Thickness(5f, 0, 0, 0)
                        }
                    }
                });

                _jobCategories[(faction.ID, department.ID)] = category;
                faction_tabs[faction].AddChild(category);
            }

            foreach (var jobAssignment in _factions.ListFactionJobs()
                                                .Where(p => (p.Faction == faction) && department.Roles.Contains(p.Job))
                                                .OrderBy(p => p.Weight)
                                                .ThenBy(p => p.Job))
            {
                if (!_prototypeManager.TryIndex<JobPrototype>(jobAssignment.Job, out var job))
                    continue;

                var jobContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };

                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center
                };
                var jobIcon = _prototypeManager.Index(_factions.OverrideJobIcon(jobAssignment));
                icon.Texture = jobIcon.Icon.Frame0();
                selector.Setup(selectorPriorities, _factions.OverrideLocalizedJobName(jobAssignment), 200, _factions.OverrideLocalizedJobDescription(jobAssignment), icon, job.Guides);

                // This shouldn't depend on any character specific properties, so pass null
                if (!_requirements.IsAllowed(job, null, out var reason))
                {
                    selector.LockRequirements(reason);
                    SelectedJobPriorities[(faction, job)] = JobPriority.Never;
                    CheckDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += selectedPrio =>
                {
                    var selectedJobPrio = (JobPriority) selectedPrio;

                    SelectedJobPriorities[(faction, job)] = selectedJobPrio;

                    foreach (var ((factionID, jobId), other) in _jobPriorities)
                    {
                        // Sync other selectors with the same job in case of multiple department jobs
                        if (jobId == job.ID)
                        {
                            other.Select(selectedPrio);
                            continue;
                        }

                        if (selectedJobPrio == JobPriority.High && (JobPriority) other.Selected == JobPriority.High)
                        {
                            // Lower any other high priorities to medium.
                            other.Select((int)JobPriority.Medium);
                            SelectedJobPriorities[(factionID, jobId)] = JobPriority.Medium;
                        }
                    }

                    UpdateJobPriorities();
                    CheckDirty();
                };

                _jobPriorities.Add(((faction, job), selector));
                jobContainer.AddChild(selector);
                category.AddChild(jobContainer);
            }

            faction_tabs[dptAssignment.Faction].AddChild(new Control
            {
                MinSize = new Vector2(0, 23),
            });
        }

        UpdateJobPriorities();
        CheckDirty();
    }

    /// <summary>
    /// Updates selected job priorities to the priority selectors.
    /// </summary>
    private void UpdateJobPriorities()
    {
        foreach (var ((faction, job), prioritySelector) in _jobPriorities)
        {
            prioritySelector.Select((int) SelectedJobPriorities.GetValueOrDefault((faction, job)));
        }
    }

    /// <summary>
    /// Check if the selected priorities are different from the saved ones
    /// </summary>
    private void CheckDirty()
    {
        // If it equals default then reset the button.
        var savedJobPriorities = _preferencesManager.Preferences?.JobPriorities ?? [];
        if (!SelectedJobPriorities.Keys.ToHashSet().SetEquals(savedJobPriorities.Keys.ToHashSet()))
        {
            SetDirty(true);
            return;
        }

        foreach (var (job, prio) in SelectedJobPriorities)
        {
            if (prio != savedJobPriorities.GetValueOrDefault(job))
            {
                SetDirty(true);
                return;
            }
        }

        SetDirty(false);
    }

    /// <summary>
    /// Private member that should be only set via <see cref="SetDirty"/>
    /// </summary>
    private bool _isDirty;

    /// <summary>
    /// True if the current set of priorities is different from the saved ones.
    /// Used to determine if the save and reset buttons should be active.
    /// <seealso cref="_isDirty"/>
    /// </summary>
    public bool IsDirty()
    {
        return _isDirty;
    }

    /// <summary>
    /// Set the dirty state of the Job Priority Editor, will also set the disabled state of the reset and save buttons
    /// afterwards appropriately
    /// </summary>
    /// <param name="value">True if you made a change which makes the current job priorities differ from the saved ones.
    /// False if you made a change which makes them equal, or if you reset the job priorities or saved them.</param>
    private void SetDirty(bool value)
    {
        if (_isDirty == value)
            return;

        _isDirty = value;
        UpdateSaveButton();
    }

    /// <summary>
    /// Sets the disabled state of the reset and save buttons according to <see cref="IsDirty"/>.
    /// </summary>
    private void UpdateSaveButton()
    {
        SaveButton.Disabled = !IsDirty();
        ResetButton.Disabled = !IsDirty();
    }

    /// <summary>
    /// Load the job priorities from the preferences manager into the editor
    /// </summary>
    public void LoadJobPriorities()
    {
        SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone() ??  [];
        UpdateJobPriorities();
        CheckDirty();
    }
}

