using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.LimbDamage;
using Content.Shared._FarHorizons.LimbDamage.Components;
using Content.Shared.Atmos;
using Content.Shared.Body;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared._FarHorizons.Medical.Disease.Components; //FarHorizons

namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private static readonly Color Green = Color.FromHex("#00FF00"); // Starlight
    private static readonly Color Red = Color.FromHex("#FF0000"); // Starlight
    
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;
    private readonly LimbDamageSystem _limbDamage; // Far Horizons
    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed; // Far Horizons

    private ProtoId<OrganCategoryPrototype> _currTarget = "Torso";
    private static ProtoId<OrganCategoryPrototype> _defaultLimb = "Torso";

    private EntityUid? _targetEnt = null;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
        _limbDamage = _entityManager.System<LimbDamageSystem>(); // Far Horizons

        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a); // Far Horizons
        LimbTargettingDisplay.OnSelectedLimb += SetLimbTarget;
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        _targetEnt = _entityManager.GetEntity(state.TargetEntity);

        if (_targetEnt == null
            || !_entityManager.TryGetComponent<DamageableComponent>(_targetEnt, out var damageable))
        {
            NoPatientDataText.Visible = true;
            return;
        }

        NoPatientDataText.Visible = false;

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        // SpriteView.SetEntity(target.Value);
        // SpriteView.Visible = msg.State.ScanMode.HasValue && msg.State.ScanMode.Value;
        // NoDataTex.Visible = !SpriteView.Visible;
        ProtoId<LimbTargettingPrototype> limbTargetVisuals = "LimbTargetHuman";
        if (_entityManager.TryGetComponent<LimbDamageableComponent>(_targetEnt, out var limbDamageable))
            limbTargetVisuals = limbDamageable.Proto;
        
        LimbTargettingDisplay.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !LimbTargettingDisplay.Visible;
        LimbTargettingDisplay.InitTarget(_prototypes, _cache, _spriteSystem, limbTargetVisuals);

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(_targetEnt.Value)
            ? Identity.Name(_targetEnt.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(_targetEnt.Value, out var humanoidProfileComponent)
                ? string.IsNullOrEmpty(humanoidProfileComponent.CustomSpeciesName)
                    ? Loc.GetString(_prototypes.Index(humanoidProfileComponent.Species).Name)
                    : humanoidProfileComponent.CustomSpeciesName + " (" +
                      Loc.GetString(_prototypes.Index(humanoidProfileComponent.Species).Name) + ")"
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        // Starlight begin - blood level color gradient and exclaimation marks to show severity
        if (!float.IsNaN(state.BloodLevel))
        {
            var bloodPercent = state.BloodLevel;
            var exclamations = bloodPercent switch {
                <= 0f => "!!!!",
                <= 0.25f => "!!!",
                <= 0.5f => "!!",
                <= 0.75f => "!",
                _ => ""
            };
            
            BloodLabel.Text = $"{bloodPercent * 100:F1}% {exclamations}";
            
            // Color gradient: Goes from green at 100% to red at 50% then stays red.
            var clampedPercent = Math.Max(bloodPercent, 0.5f);
            var scaled = (clampedPercent - 0.5f) / 0.5f;
            BloodLabel.FontColorOverride = Color.InterpolateBetween(Red, Green, scaled);
        }
        // Starlight end
        else
        {
            BloodLabel.Text = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            BloodLabel.FontColorOverride = null;
        }

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(_targetEnt.Value, out var mobStateComponent)
                ? GetStatus(mobStateComponent.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Starlight end

        // Far Horizons Start
        var infected = false;

        if (_entityManager.TryGetComponent<DiseaseCarrierComponent>(_targetEnt.Value, out var carrier)
            && !string.IsNullOrEmpty(carrier.DiseaseIcon)
            && _prototypes.TryIndex(carrier.DiseaseIcon, out var healthIcon))
        {
            infected = true;
            DiseaseIcon.Visible = true;
            DiseaseIcon.Texture = _spriteSystem.Frame0(healthIcon.Icon);
        }
        else
        {
            DiseaseIcon.Visible = false;
            DiseaseIcon.ToolTip = null;
        }

        DiseaseLabel.Text = infected
            ? Loc.GetString("health-analyzer-window-entity-disease-yes")
            : Loc.GetString("health-analyzer-window-entity-disease-no");

        DrawMetabolizingChemicals(state.MetabolizingReagents);
        
        Repopulate();
        // Far Horizons End
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.ActiveCritical => Loc.GetString("health-analyzer-window-entity-critical-text"), // Far Horizons
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    // Starlight begin - Draw Damage Groups in a two column grid in their own boxes.
    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        var gridContainer = new GridContainer
        {
            Columns = 2,
        };

        GroupsContainer.AddChild(gridContainer);

        var columnIndex = 0;
        foreach (var (damageGroupId, damageAmount) in groups)
        {
            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            // Create a bordered box for each damage group
            var groupBox = new PanelContainer
            {
                Margin = new Thickness(2),
                MinWidth = 155,
            };

            // Boxes in the second column get right aligned
            if (columnIndex % 2 == 1)
            {
                groupBox.HorizontalAlignment = HAlignment.Right;
            }

            groupBox.PanelOverride = new StyleBoxFlat
            {
                BorderColor = Color.Gray,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            var titleRow = CreateDiagnosticGroupTitleRow(groupTitleText, (float)damageAmount, damageGroupId);
            groupContainer.AddChild(titleRow);

            // Add divider line under the title row
            var divider = new PanelContainer
            {
                MinHeight = 1,
                Margin = new Thickness(0, 0, 0, 4),
            };
            divider.PanelOverride = new StyleBoxFlat(Color.Gray);
            groupContainer.AddChild(divider);

            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageTypeName = _prototypes.Index<DamageTypePrototype>(type).LocalizedName;
                var typeId = type.ToString().ToLowerInvariant();

                var damageRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(0, 2),
                };

                // Add damage type icon
                damageRow.AddChild(new TextureRect
                {
                    SetSize = new Vector2(15, 15),
                    Texture = GetTexture(typeId),
                    Margin = new Thickness(0, 0, 4, 0),
                });

                var typeLabel = new Label
                {
                    Text = damageTypeName,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Left,
                };

                var amountLabel = new Label
                {
                    Text = typeAmount.ToString(),
                    HorizontalAlignment = HAlignment.Right,
                };

                damageRow.AddChild(typeLabel);
                damageRow.AddChild(amountLabel);
                groupContainer.AddChild(damageRow);
            }

            groupBox.AddChild(groupContainer);
            gridContainer.AddChild(groupBox);
            columnIndex++;
        }
    }

    // Metabolizing chemicals display
    private void DrawMetabolizingChemicals(List<(string ReagentId, FixedPoint2 Quantity)>? reagents)
    {
        ChemicalsContainer.RemoveAllChildren();

        var hasChemicals = reagents != null && reagents.Count > 0;

        ChemicalsDivider.Visible = hasChemicals;
        ChemicalsContainer.Visible = hasChemicals;

        if (!hasChemicals || reagents == null)
            return;

        // Sort by quantity descending
        var sortedReagents = reagents.OrderByDescending(r => r.Quantity).ToList();

        foreach (var reagent in sortedReagents)
        {
            var reagentName = reagent.ReagentId;
            var reagentColor = Color.White;

            if (_prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var reagentProto))
            {
                reagentName = reagentProto.LocalizedName;
                reagentColor = reagentProto.SubstanceColor;
                
            }

            var rowContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2),
            };

            // Color bar
            var colorBar = new PanelContainer
            {
                MinWidth = 10,
                MinHeight = 16,
                Margin = new Thickness(0, 0, 6, 0),
            };
            colorBar.PanelOverride = new StyleBoxFlat(reagentColor);

            var nameLabel = new Label
            {
                Text = reagentName,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
            };

            var quantityLabel = new Label
            {
                Text = $"{reagent.Quantity}u",
                HorizontalAlignment = HAlignment.Right,
            };

            rowContainer.AddChild(colorBar);
            rowContainer.AddChild(nameLabel);
            rowContainer.AddChild(quantityLabel);
            ChemicalsContainer.AddChild(rowContainer);
        }
    }
    // Starlight end

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/_Starlight/Objects/Devices/health_analyzer.rsi"); // Starlight - new rsi for new icons :)
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    // Starlight begin - damage group titles get a color gradient and exclamations to indicate severity 
    private BoxContainer CreateDiagnosticGroupTitleRow(string text, float damageAmount, string damageGroupId)
    {
        // Color gradient: green (0) -> red (100+)
        var clampedDamage = Math.Min(damageAmount, 100f);
        var damagePercent = clampedDamage / 100f;
        
        var titleColor = Color.InterpolateBetween(Green, Red, damagePercent);
        
        var exclamations = damageAmount switch {
            > 200f => " !!!!",
            > 100f => " !!!",
            > 75f => " !!",
            > 50f => " !",
            _ => ""
        };
        var titleRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 4),
        };
        
        var groupId = damageGroupId.ToLowerInvariant();
        
        // Add damage group icon
        titleRow.AddChild(new TextureRect
        {
            SetSize = new Vector2(15, 15),
            Texture = GetTexture(groupId),
            Margin = new Thickness(0, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
        });
        
        var titleLabel = new Label
        {
            Text = text + exclamations,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = titleColor,
        };
        
        titleRow.AddChild(titleLabel);
        
        return titleRow;
    }
    // Starlight end
    //FarHorizons Start
    public void SetEntity(EntityUid uid)
    {
        if (!_entityManager.HasComponent<ResearchClientComponent>(uid))
        {
            ServerListButton.Visible = false;
        }
    }

    private void SetLimbTarget(ProtoId<OrganCategoryPrototype> target)
    {
        _currTarget = target;
        LimbTargettingDisplay.UpdateLimb(_currTarget);
        Repopulate();
    }

    private void Repopulate()
    {
        if (_targetEnt == null)
            return;

        if (!_entityManager.HasComponent<LimbDamageableComponent>(_targetEnt.Value))
            LimbTargettingDisplay.Visible = false;

        var fullBodyDamage = _limbDamage.TryGetFullBodyDamage(_targetEnt.Value);
        var fullBodyDamageGroups = _limbDamage.TryGetFullBodyDamageGroups(_targetEnt.Value);

        if (fullBodyDamage == null ||
            fullBodyDamageGroups == null)
            return;

        if (!fullBodyDamage.ContainsKey(_currTarget))
            _currTarget = _defaultLimb;

        LimbTargettingDisplay.SetHealth(fullBodyDamage.ToDictionary(p => p.Key, p => p.Value.Sum(e => (float)e.Value)));

        // Total Damage

        DamageLabel.Text = fullBodyDamage[_currTarget].Select(p => (float)p.Value).Sum().ToString();
        
        // Damage Groups

        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damagePerType = fullBodyDamage[_currTarget];

        var groupOrder = new List<string> { "Burn", "Brute", "Airloss", "Toxin", "Genetic" };
        var sortedGroups = fullBodyDamageGroups[_currTarget]
            .OrderBy(g => groupOrder.IndexOf(g.Key))
            .ToDictionary(g => g.Key, g => g.Value);

        DrawDiagnosticGroups(sortedGroups, damagePerType);

        StatusText.Visible = _currTarget == _defaultLimb;
        StatusLabel.Visible = _currTarget == _defaultLimb;
        TemperatureText.Visible = _currTarget == _defaultLimb;
        TemperatureLabel.Visible = _currTarget == _defaultLimb;
        BloodText.Visible = _currTarget == _defaultLimb;
        BloodLabel.Visible = _currTarget == _defaultLimb;
        DiseaseText.Visible = _currTarget == _defaultLimb;
        DiseaseContainer.Visible = _currTarget == _defaultLimb;
        ChemicalsContainer.Visible = _currTarget == _defaultLimb;
    }
    //FarHorizons End
}
