using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed; //FarHorizons

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        HealthAnalyzer.OnServerListButtonPressed += a => OnServerListButtonPressed?.Invoke(a); // FarHorizons
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }

    //FarHorizons Start
    public void SetEntity(EntityUid uid) => 
        HealthAnalyzer.SetEntity(uid);
    //FarHorizons End
}