## Static recipes

- type: latheRecipePack
  id: StarlightSecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: StarlightSecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
#  - MagazineBoxLightRiflePractice - FH Edit
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
#  - MagazineBoxCaselessRiflePractice - FH Edit
  - MagazineBoxRifle5.56Practice #FH
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - WeaponFlareGunSecurity

- type: latheRecipePack
  id: StarlightSecurityAmmoEmagStatic
  recipes:
  - L6SawMagazine

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoStatic
  recipes:
######################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleSP
  - MagazineBoxLightRifleHP
  - MagazineBoxLightRifleFMJ
# Magnum
  - MagazineBoxMagnumSP
  - MagazineBoxMagnumHP
  - MagazineBoxMagnumFMJ
# Pistol
#  - MagazineBoxCaselessRifle - FH Edit
#  - MagazineBoxCaselessRifleRubber - FH Edit
  - MagazineBoxPistolSP
  - MagazineBoxPistolHP
  - MagazineBoxPistolFMJ
  - MagazineBoxRevolver38SP #FH
  - MagazineBoxRevolver38HP #FH
  - MagazineBoxRevolver38FMJ #FH
# Rifle
  - MagazineBoxRifle5.56SP #FH
  - MagazineBoxRifle5.56HP #FH
  - MagazineBoxRifle5.56FMJ #FH
# Shotgun
  - BoxLethalshot
  - BoxShotgunSlug
  - BoxShellTranquilizer
#####################MAGAZINE#######################
# LMG
  - LightRifleHeavyMagazineSP
  - LightRifleHeavyMagazineHP
  - LightRifleHeavyMagazineFMJ
  - LightRifleHeavyMagazineEmpty
# Light Rifle
#  - MagazineLightRifleSP - FH Edit
#  - MagazineLightRifleHP - FH Edit
#  - MagazineLightRifleFMJ - FH Edit
#  - MagazineLightRifleMaxim - FH Edit
  - SpeedLoaderLightRifle
#  - MagazineLightRifleEmpty - FH Edit
# Magnum
  - SpeedLoaderMagnumSP
  - SpeedLoaderMagnumHP
  - SpeedLoaderMagnumFMJ
  - MagazineMagnum
#  - MagazineMagnumRifleSP - FH Edit
  - MagazineMagnumEmpty
  - SpeedLoaderMagnumEmpty
# Pistol
  #- MagazinePistolCaselessRifle
  #- MagazineCaselessRifleRubber
  - MagazinePistolSP
  - MagazinePistolHP
  - MagazinePistolFMJ
  - MagazinePistolEmpty
  - MagazinePistol38SP # FH Edit
  - MagazinePistol38HP # FH Edit
  - MagazinePistol38FMJ # FH Edit
  - MagazinePistol38Empty # FH Edit
# SMG
  - MagazinePistolSubMachineGunSP
  - MagazinePistolSubMachineGunHP
  - MagazinePistolSubMachineGunFMJ
  - MagazinePistolSubMachineGunEmpty
#  - MagazinePistolSubMachineGunTopMounted - FH edit
#  - MagazinePistolSubMachineGunTopMountedEmpty - FH edit
#  - MagazinePistolSubMachineGunUzi - FH edit
#  - MagazinePistolSubMachineGunPPSH - FH edit
# Rifle
  - MagazineRifle5.56SP #FH
  - MagazineRifle5.56HP #FH
  - MagazineRifle5.56FMJ #FH
  - MagazineRifle5.56Empty #FH
# Shotgun
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoaderMagnumBasic
  - SpeedLoaderShotgunEmpty
  - SpeedLoaderShotgunSlug
  - SpeedLoaderShotgunBeanbag
####################################################

- type: latheRecipePack
  id: StarlightSecurityEmagWeaponsStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: StarlightDefenseStatic
  recipes:
  - EnergyDomeTurtle

- type: latheRecipePack
  id: StarlightSecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield

- type: latheRecipePack
  id: StarlightSecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  - ScanGateMachineCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: StarlightSecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoDynamic
  recipes:
#####################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxLightRifleAP
# Magnum
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxMagnumAP
# Pistol
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxPistolAP
  - MagazineBoxRevolver38AP #FH
# Rifle
  - MagazineBoxRifle5.56Incendiary #FH
  - MagazineBoxRifle5.56Uranium #FH
  - MagazineBoxRifle5.56AP #FH
# Shotgun
  - BoxShotgunIncendiary
  - BoxShotgunUranium
#####################MAGAZINE#######################
# LMG
  - LightRifleHeavyMagazineIncendiary
  - LightRifleHeavyMagazineUranium
  - LightRifleHeavyMagazineAP
# Light Rifle
#  - MagazineLightRifleIncendiary - FH Edit
#  - MagazineLightRifleUranium - FH Edit
#  - MagazineLightRifleAP - FH Edit
# Magnum
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
  - SpeedLoaderMagnumAP
# Pistol
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolAP
  - MagazinePistol38AP # FH Edit
# SMG
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazinePistolSubMachineGunAP
# Rifle
  - MagazineRifle5.56Incendiary #FH
  - MagazineRifle5.56Uranium #FH
  - MagazineRifle5.56AP #FH
# Shotgun
  #- MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderShotgunIncendiary
  - SpeedLoaderShotgunUranium
# Grenade
  - MagazineGrenadeEmpty

- type: latheRecipePack
  id: StarlightSecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponIonRifle
  - WeaponIonCarbine
  - WeaponDecloner
  - WeaponLaserImmolator
  - WeaponLaserSvalinn
  - WeaponTemperatureGun

- type: latheRecipePack
  id: StarlightSecurityMechsWeapons
  recipes:
  - WeaponMechCombatMissileRack8
  - WeaponMechCombatShotgun
  - WeaponMechCombatShotgunIncendiary
  - WeaponMechCombatUltraRifle
  - WeaponMechCombatXray
  - WeaponMechChainSword
  - WeaponMechCombatIon
  - WeaponMechCombatAMLG90
#  - WeaponMechCombatDisabler
#  - WeaponMechCombatFlashbangLauncher
#  - WeaponMechCombatTaser
  - WeaponMechCombatImmolationGun
  - WeaponMechCombatSolarisLaser
  - WeaponMechCombatFiredartLaser

- type: latheRecipePack
  id: StarlightSecurityMechsSystems
  recipes:
  - MechEquipmentSecGrabber
  
- type: latheRecipePack
  id: StarlightSecurityMechs
  recipes:
  - GygaxHarness
  - GygaxArmor
  - GygaxHead
  - GygaxLArm
  - GygaxLLeg
  - GygaxRArm
  - GygaxRLeg
  - GygaxCentralElectronics
  - GygaxPeripheralsElectronics
  - GygaxTargetingElectronics

  - DurandHarness
  - DurandArmor
  - DurandHead
  - DurandLArm
  - DurandLLeg
  - DurandRArm
  - DurandRLeg
  - DurandCentralElectronics
  - DurandPeripheralsElectronics
  - DurandTargetingElectronics

- type: latheRecipePack
  id: SecurityCyberLimbs
  recipes:
  - LeftArmCyberBulwark
  - RightArmCyberBulwark
