- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  # Starlight start
  requirements:
  - !type:OverallPlaytimeRequirement #Far Horizons
    time: 7200 # 2 hours - Far Horizons
  #- !type:RoleTimeRequirement #Far Horizons
  #  role: JobSalvageSpecialist
  #  time: 3h
  playTimeTracker: AntagDragon
  # Starlight end
