- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
  requirements:
  #- !type:OverallPlaytimeRequirement #Far Horizons
  #  time: 86400 # 24h STARLIGHT
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 3600 # 1 hour - Far Horizons // 21600 # 6h STARLIGHT
