- type: entity
  id: SyndicateAutolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: EVIL autolathe machine board #TODO: Better Name
  description: A machine printed circuit board for an autolathe.
  components:
    - type: MachineBoard
      prototype: SyndicateAutolathe
      stackRequirements:
        Manipulator: 4
        Glass: 1