using System.Text.RegularExpressions;
using Content.Shared._Starlight.Character.Info.Components;
using Content.Shared.Mind;
using Content.Shared.Roles.Jobs;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterBackgroundInfoControl : Control
{
    private static readonly Regex Pattern = new("([a-z])([A-Z])");

    public CharacterBackgroundInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid? viewer = null)
    {
        if (!target.HasValue)
        {
            ClearCharacter();
            return;
        }
        if (entityManager.TryGetComponent<TagComponent>(target, out var comp))
        {
            if (comp == null) return;

            BackgroundLabel.Text = "No background.";

            foreach (var tag in comp.Tags)
            {
                if (tag.ToString().EndsWith("TraitBackground", StringComparison.Ordinal))
                {
                    Background.Text = Loc.GetString(ToLocale(tag.ToString()));
                    BackgroundLabel.Text = "Background:";
                    break;
                }
            }
        }
    }

    static string ToLocale(string input)
    {
        input = input.Replace("TraitBackground", "");
        string kebab = Pattern.Replace(input, "$1-$2");
        return $"trait-background-{kebab}-name";
    }

    public void ClearCharacter()
    {
        Background.Text = null;
    }
}