- type: entity
  id: LockerSecurityFHFilled
  suffix: Filled
  parent: LockerSecurityFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesSecurityRed
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
  
- type: entity
  id: LockerSecurityLargeFHFilled
  suffix: Filled
  parent: LockerSecurityLargeFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHLFilled
  suffix: Filled, Left
  parent: LockerSecurityLargeFHL
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHMFilled
  suffix: Filled, Middle
  parent: LockerSecurityLargeFHM
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 3
      - id: WeaponDisabler
        amount: 3
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.9
      - id: ClothingHeadHelmetBasic
        amount: 3
      - id: ClothingOuterArmorBasic
        amount: 3
      - id: ClothingBeltSecurityFilled
        amount: 3
      - id: Flash
        amount: 3
      - id: ClothingEyesGlassesSecurity
        amount: 3
      - id: ClothingEyesHudSecurity
        amount: 3
      - id: ClothingHeadsetSecurity
        amount: 3
      - id: ClothingHandsGlovesSecurityRed
        amount: 3
      - id: ClothingShoesBootsJack
        amount: 3
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 3
      - id: BookSpaceLaw
        amount: 3

- type: entity
  id: LockerSecurityLargeFHRFilled
  suffix: Filled, Right
  parent: LockerSecurityLargeFHR
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerWardenFHFilled
  suffix: Filled
  parent: LockerWardenFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponEnergyShotgun
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingHeadsetSecurityWarden
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars

- type: entity
  id: LockerWardenLargeFHFilled
  suffix: Filled
  parent: LockerWardenLargeFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponEnergyShotgun
      - id: WeaponDisabler
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHandsGlovesCombat
        amount: 2
      - id: ClothingHeadsetSecurityWarden
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: ClothingOuterCoatWarden
        amount: 2
      - id: ClothingOuterWinterWarden
        amount: 2
      - id: RubberStampWarden
        amount: 2
      - id: DoorRemoteArmory
        amount: 2
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2
      - id: ClothingBackpackElectropack
        amount: 4
      - id: RemoteSignaller
        amount: 4
      - id: Binoculars
        amount: 2

- type: entity
  id: LockerBrigmedicLargeFHFilled
  suffix: Filled
  parent: LockerBrigmedicLargeFH
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedic
        amount: 2
      - id: ClothingEyesHudBrigmedic
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: TrackingImplanter
        amount: 4
      - id: ClothingOuterHardsuitBrigmedic
        amount: 2
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatCorpsman
      - id: ClothingUniformJumpsuitCorpsman
      - id: ClothingUniformJumpskirtCorpsman
      - id: ClothingBeltCorpsmanFilled
      - id: ClothingHandsGlovesBlackNitrile
      - id: ClothingShoesBootsMagSec
        amount: 2
      - id: BedsheetBrigmedicStrange
      - id: BedsheetBrigmedic
      - id: MedkitFilled
        amount: 2
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: MedkitBurnFilled
        prob: 0.7
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic
        amount: 2
      - id: PlushieMorgana
      - id: PlushieKiller

- type: entity
  id: LockerBrigmedicFHFilled
  suffix: Filled
  parent: LockerBrigmedicFH
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedic
      - id: ClothingEyesHudBrigmedic
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatCorpsman
      - id: ClothingUniformJumpsuitCorpsman
      - id: ClothingUniformJumpskirtCorpsman
      - id: ClothingBeltCorpsmanFilled
      - id: ClothingHandsGlovesBlackNitrile
      - id: ClothingShoesBootsMagSec
      - id: BedsheetBrigmedicStrange
      - id: BedsheetBrigmedic
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic
      - id: PlushieMorgana
      - id: PlushieKiller

- type: entity
  id: LockerHeadOfSecurityFHFilled
  suffix: Filled
  parent: LockerHeadOfSecurityFH
  components:
  - type: StorageFill
    contents:
    - id: ClothingNeckCloakHosElite
    - id: WeaponEnergySMG
    - id: BookSpaceLaw
    - id: BoxEncryptionKeySecurity
    - id: CigarGoldCase
    - id: ClothingBeltSecurityFilled
    - id: ClothingEyesGlassesSecurity
    - id: ClothingEyesHudSecurity
    - id: ClothingHeadsetAltSecurity
    - id: ClothingMaskNeckGaiter
    - id: ClothingOuterCoatHoSTrench
    - id: ClothingShoesBootsJack
    - id: DoorRemoteSecurity
    - id: HoloprojectorSecurity
    - id: RubberStampHos
    - id: SecurityTechFabCircuitboard
    - id: CargoRequestSecurityComputerCircuitboard
    - id: WeaponDisabler
    - id: WantedListCartridge
    - id: DrinkHosFlask

- type: entity
  id: LockerHeadOfSecurityFHFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerHeadOfSecurityFH
  components:
  - type: StorageFill
    contents:
    - id: ClothingNeckCloakHosElite
    - id: WeaponEnergySMG
    - id: BookSpaceLaw
    - id: BoxEncryptionKeySecurity
    - id: CigarGoldCase
    - id: ClothingBeltSecurityFilled
    - id: ClothingEyesGlassesSecurity
    - id: ClothingEyesHudSecurity
    - id: ClothingHeadsetAltSecurity
    - id: ClothingMaskNeckGaiter
    - id: ClothingOuterCoatHoSTrench
    - id: ClothingShoesBootsJack
    - id: DoorRemoteSecurity
    - id: HoloprojectorSecurity
    - id: RubberStampHos
    - id: SecurityTechFabCircuitboard
    - id: CargoRequestSecurityComputerCircuitboard
    - id: WeaponDisabler
    - id: WantedListCartridge
    - id: DrinkHosFlask
    - id: ClothingMaskGasSwat
    - id: ClothingOuterHardsuitSecurityRed
    - id: JetpackSecurityFilled
    - id: OxygenTankFilled
    - id: ClothingShoesBootsMagSec