- type: department
  id: Law
  name: faction-neutral-department-Law #Far Horizons
  description: department-Law-description
  color: "#ff178b"
  weight: -10
  roles:
  - Magistrate
  - IAA
  
- type: department
  id: Representives
  name: faction-nt-department-Representives #Far Horizons
  description: department-Representives-description
  color: "#05255D"
  roles:
  - BlueShield
  - NanoTrasenRepresentative
  - Decimus
  - NanoTrasenSpecialForces
  primary: false
  weight: 50
