name: Build & Test Debug

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ Far-Horizons ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.yml'
      - '**.yaml'

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-test-env

    - name: Run Content.Tests
      run: dotnet test --no-build -c DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0
  
  integration-tests:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"
    needs: unit-tests
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-test-env

    - name: Run Content.IntegrationTests
      env:
        DOTNET_gcServer: "0"
        DOTNET_GCHeapHardLimitPercent: "65"
      run: dotnet test --no-build -c DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj --settings .farhorizons/.integrationtests

