name: Build & Test Debug

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ Far-Horizons ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.yml'
      - '**.yaml'

jobs:
  test:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Build Project
      run: dotnet build -c DebugOpt

    - name: Run Content.Tests
      run: dotnet test --no-build -c DebugOpt Content.Tests/Content.Tests.csproj --logger trx -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        $env:DOTNET_gcServer=0
        $env:DOTNET_GCHeapHardLimitPercent=60
        dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj --logger trx -- NUnit.ConsoleOut=0 NUnit.NumberOfTestWorkers=1 NUnit.RetryCount=1 NUnit.MapWarningTo=Failed
