name: Discord Publish

concurrency:
  group: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml
    - uses: actions/checkout@v3
    - name: Publish changelog (Discord)
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_PATCHNOTES_WEBHOOK }}
        DISCORD_CHANGELOG_ROLE_ID: "1423332975688286308"
