name: Discord Publish

concurrency:
  group: publish

on:
  push:
    branches:
      - Far-Horizons
    paths:
      - 'Resources/Changelog/ChangelogFarHorizons.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-git
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Publish changelog (Discord)
      run: Tools/actions_live_changelog.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_PATCHNOTES_WEBHOOK }}
        CHANGELOG_FILE: Resources/Changelog/ChangelogFarHorizons.yml
