name: Discord Publish

concurrency:
  group: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml
    - uses: actions/checkout@v3
    - name: Publish changelog (Discord)
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_PATCHNOTES_WEBHOOK }}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ github.token }}
        commit-message: Discord metadata update [skip ci]
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        signoff: false
        branch: patch-changelog-backfill
        delete-branch: true
        title: '[CI] Update discord metadata for patchnotes'
        body: |
          Automated PR to populate patchnotes
        labels: |
          automated pr