name: Test

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ Far-Horizons ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.slnx'
      - '**.yml'
      - '**.yaml'

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:  
  yaml-lint:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-test-env
      - run: dotnet run --no-build -c DebugOpt --project Content.YAMLLinter/Content.YAMLLinter.csproj
  
  unit-tests:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-test-env
      - run: dotnet test --no-build -c DebugOpt Content.Tests/Content.Tests.csproj --settings .farhorizons/.integrationtests
  
  integration-tests:
    if: "!contains(github.event.pull_request.labels.*.name, 'automated pr') && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
      - uses: ./.github/actions/setup-test-env
      - run: dotnet test --no-build -c DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj --settings .farhorizons/.integrationtests
        env:
          DOTNET_gcServer: "0"
      - if: failure() # Check for OOMKiller on fail
        run: dmesg | grep -i "out of memory" || true