- type: job
  id: MiningSpecialist
  name: job-name-miningspec
  description: job-description-miningspec
  playTimeTracker: JobMiningSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: Cargo
    time: 10800 # 3 hrs
  - !type:OverallPlaytimeRequirement
    time: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: MiningSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Mining
  - Maintenance
  - External
  extendedAccess:
  - Salvage

- type: startingGear
  id: MiningSpecialistGear
  equipment:
    #id: MiningPDA #Far Horizons - Disabling because they can choose between PDA's in loadout.
    ears: ClothingHeadsetMining
    belt: ClothingBeltSalvageWebbing #Far Horizons
    gloves: ClothingHandsGlovesCargo #Far Horizons
  storage: #Far Horizons
    back:
    - OreBag # Unfortunately this just drops to the ground and I don't feel like changing that fact. -Corrupt

- type: chameleonOutfit
  id: MiningSpecialistChameleonOutfit
  job: MiningSpecialist
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    belt: ClothingBeltSalvageWebbing #Far Horizons
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesCargo #Far Horizons
